{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "2876e869-4098-4f01-8f11-2da335ffa963",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-09-26 10:19:32.182 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:32.184 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.001 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\sreet\\Documents\\anaconda installation\\envs\\aidl\\lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2024-09-26 10:19:34.002 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.004 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.006 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.027 Session state does not function when running a script without `streamlit run`\n",
      "2024-09-26 10:19:34.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.029 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.030 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.031 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.033 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.037 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.039 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.048 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.053 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.058 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.062 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.063 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.064 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.065 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.067 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.069 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.076 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.081 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.092 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.097 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.103 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.110 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.111 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.112 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.115 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.123 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.124 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.125 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.126 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.129 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.131 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.133 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.133 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.134 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.135 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.137 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.140 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.147 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.148 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.149 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-09-26 10:19:34.150 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pickle\n",
    "import streamlit as st\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "## Load the model\n",
    "model = pickle.load(open('rf.pkl', 'rb'))\n",
    "\n",
    "#Streamlit app setup\n",
    "st.set_page_config(page_title='Segmentation of Customers', layout='centered')\n",
    "st.title('Segmentation of Customers')\n",
    "\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    <style>\n",
    "    .stApp {\n",
    "        background-color: #0077b6;\n",
    "    }\n",
    "    </style>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "st.write()\n",
    "\n",
    "def user_input():\n",
    "    Year_Birth = st.sidebar.number_input('Input Year of Birth',value=1940,step=1,format=\"%d\")\n",
    "    Education = st.sidebar.selectbox('Education', ['Basic', '2n Cycle', 'Graduation', 'Master', 'PhD'])\n",
    "    Marital_Status = st.sidebar.selectbox('Marital Status', ['Single', 'Together', 'Married', 'Divorced'])\n",
    "    Income = st.sidebar.number_input('Input Household Income',value=0,step=1,format=\"%d\")\n",
    "    Kidhome = st.sidebar.radio('Select Number Of Kids In Household', [0, 1, 2])\n",
    "    Teenhome = st.sidebar.radio('Select Number Of Teens In Household', [0, 1, 2])\n",
    "    MntWines = st.sidebar.number_input('Amount spent on Wine in last 2 years',value=0,step=1,format=\"%d\")\n",
    "    MntFruits = st.sidebar.number_input('Amount spent on Fruits in last 2 years',value=0,step=1,format=\"%d\")\n",
    "    MntMeatProducts = st.sidebar.number_input('Amount spent on Meat in last 2 years',value=0,step=1,format=\"%d\")\n",
    "    MntFishProducts = st.sidebar.number_input('Amount spent on Fish in last 2 years',value=0,step=1,format=\"%d\")\n",
    "    MntSweetProducts = st.sidebar.number_input('Amount spent on Sweet in last 2 years',value=0,step=1,format=\"%d\")\n",
    "    MntGoldProds = st.sidebar.number_input('Amount spent on Gold in last 2 years',value=0,step=1,format=\"%d\")\n",
    "    NumWebPurchases = st.sidebar.number_input('Number of purchases made through Company website',value=0,step=1,format=\"%d\")\n",
    "    NumCatalogPurchases = st.sidebar.number_input('Number of purchases made using a catalogue',value=0,step=1,format=\"%d\")\n",
    "    NumStorePurchases = st.sidebar.number_input('Number of purchases made directly in store',value=0,step=1,format=\"%d\")\n",
    "\n",
    "    data = {\n",
    "        'Year_Birth': Year_Birth,\n",
    "        'Education': Education,\n",
    "        'Marital_Status': Marital_Status,\n",
    "        'Income': Income,\n",
    "        'Kidhome': Kidhome,\n",
    "        'Teenhome': Teenhome,\n",
    "        'MntWines': MntWines,\n",
    "        'MntFruits': MntFruits,\n",
    "        'MntMeatProducts': MntMeatProducts,\n",
    "        'MntFishProducts': MntFishProducts,\n",
    "        'MntSweetProducts': MntSweetProducts,\n",
    "        'MntGoldProds': MntGoldProds,\n",
    "        'NumWebPurchases': NumWebPurchases,\n",
    "        'NumCatalogPurchases': NumCatalogPurchases,\n",
    "        'NumStorePurchases': NumStorePurchases\n",
    "    }\n",
    "\n",
    "    features = pd.DataFrame(data, index=[0])\n",
    "    return features\n",
    "\n",
    "def preprocess_input(features):\n",
    "    # Encode categorical features\n",
    "    education_mapping = {'Basic': 0, '2n Cycle': 1, 'Graduation': 2, 'Master': 3, 'PhD': 4}\n",
    "    marital_status_mapping = {'Single': 0, 'Together': 1, 'Married': 2, 'Divorced': 3}\n",
    "\n",
    "    features['Education'] = features['Education'].map(education_mapping)\n",
    "    features['Marital_Status'] = features['Marital_Status'].map(marital_status_mapping)\n",
    "    \n",
    "def preprocess_features(features):\n",
    "    ## Ensure the order of columns is consistent with the training data\n",
    "    columns_order = ['Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome', 'Teenhome', \n",
    "                     'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', \n",
    "                     'MntGoldProds', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases']\n",
    "\n",
    "    features = features[columns_order]\n",
    "    return features\n",
    "\n",
    "def cust_segment(features):\n",
    "     prediction = model.predict(features)\n",
    "     cluster = ''\n",
    "     if prediction[0] == 0:\n",
    "         cluster = 'Cluster 1'\n",
    "     elif prediction[1] == 1:\n",
    "         cluster = 'Cluster 2'\n",
    "     elif prediction[2] == 2:\n",
    "         cluster = 'Cluster 3'\n",
    "     return cluster\n",
    "\n",
    "## Get user input\n",
    "sub_df = user_input()\n",
    "processed_sub_df = preprocess_input(sub_df)\n",
    "\n",
    "## Predict customer segment\n",
    "if st.button(\"Segment Customer\"):\n",
    "    segment = cust_segment(processed_sub_df)\n",
    "    st.write(f'The customer belongs to {segment}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aea24e54-419f-480f-a79f-8ce76e7c3a08",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
